base:
  random_state : 42
  target_col : Output
  test_size : 0.33

app:
  host : 0.0.0.0
  port : 8080 

data:
  raw_data:
    train_batch: training_data
    pred_batch: prediction_data

  train:
    good_data_dir : good/train
    bad_data_dir: bad/train

  pred:
    good_data_dir: good/pred
    bad_data_dir: bad/pred

mongodb:
  mongo_url: 
  phising_data_db_name: scania-data
  phising_train_data_collection: scania-train-data
  phising_pred_data_collection: scania-pred-data

knn_imputer:
  n_neighbors : 3
  weights : uniform
  missing_values: nan

kmeans_cluster:
  init          : k-means++
  max_clusters  : 11
  knee_locator:
    curve     : convex
    direction : decreasing

container:
  input_files_container: input-files-for-train-and-pred
  phising_model_container: scania-model
  scania-mlflow_container: scania-mlflow
  phising_pred_data_container: scania-pred-data
  phising_train_data_container: scania-train-data
  phising_raw_data_container: scania-raw-data

models_dir:
  trained : trained/
  stag: staging/
  prod : production/

model_utils:
  verbose : 3
  cv      : 5
  n_jobs  : -1
  save_format : .sav

model_params:
  rf_model:
    n_estimators:
      - 10
      - 50
      - 100
      - 130
      
    criterion:
      - gini
      - entropy

    max_features:
      - auto
      - log2

    max_depth:
      - 2
      - 3
      - 4
      - 5

  xgb_model:
    learning_rate:
      - 0.5
      - 0.1
      - 0.01
      - 0.001

    max_depth:
      - 3
      - 5
      - 10
      - 20

    n_estimators:
      - 10
      - 50
      - 100
      - 200
    
mlflow_config:
  experiment_name : scania-ops-test
  run_name : mlops
  serialization_format : cloudpickle  
  num_of_prod_models : 3

db_log:
  db_train_log : phising_training_logs
  db_pred_log : phising_prediction_logs

train_db_log:
  model_training : model_training_log
  col_validation : train_col_validation_log
  data_transform : train_data_transform_log
  export_csv : train_export_to_csv_log
  general : train_general_log
  db_insert: train_db_insert_log
  load_prod_model : load_prod_model_log
  missing_values_in_col : train_missing_values_in_column
  name_validation : train_name_validation_log
  train_main : training_main_log
  values_from_schema : train_values_from_schema_log

pred_db_log:
  col_validation : pred_col_validation_log
  data_transform : pred_data_transform_log
  db_insert : pred_db_insert_log
  export_csv : pred_export_to_csv_log
  general : pred_general_log
  missing_values_in_col : pred_missing_values_in_column
  name_validation : pred_name_validation_log
  pred_main : prediction_main_log
  values_from_schema : pred_values_from_schema_log

schema_file:
  train_schema_file : schema_training.json
  pred_schema_file : schema_prediction.json
  
elbow_plot : K-Means_Elbow.PNG

null_values_csv_file : null_values.csv

pred_output_file : predictions.csv

regex_file: phising_regex.txt

export_csv_file:
  train : train_input_file.csv
  pred : pred_input_file.csv

templates:
  dir : templates
  index : index.html